"""Reproducible comparison harness for the R002 direct-Ada-2.9.2-oracle characterization.

Expects the following files alongside this script (all committed in this same directory):

    systematic_corpus.txt          -- generated by generate_corpus.py (deterministic, read-only)
    systematic_node_22190.txt      -- systematic_node_probe.mjs run against Node v22.19.0
    systematic_node_22232.txt      -- systematic_node_probe.mjs run against Node v22.23.2
    systematic_ada292.txt          -- oracle.cpp (built against the vendored ada-2.9.2.{h,cpp})
    systematic_pyada_400.txt       -- Python ada-url==4.0.0, two-step URL()+idna_to_unicode()
    systematic_pyada_1153.txt      -- Python ada-url==1.15.3, same two-step pipeline

Regenerate any of these by following README.md's own reproduction steps, then rerun:

    python compare_oracles.py

Never modifies any file; read-only over the files listed above.
"""

from __future__ import annotations

import io
import json
import os
import unicodedata

SCRATCH = os.path.dirname(os.path.abspath(__file__))


def load_node(path: str) -> dict[str, str | None]:
    d: dict[str, str | None] = {}
    with io.open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n").rstrip("\r")
            if "\t" not in line:
                continue
            url, val = line.split("\t", 1)
            if val == "PARSE_ERROR":
                d[url] = None
                continue
            path_str = json.loads(val)
            body = path_str.lstrip("\\")
            suffix = "\\share"
            d[url] = body[: -len(suffix)] if body.endswith(suffix) else body
    return d


def load_bare(path: str) -> dict[str, str | None]:
    d: dict[str, str | None] = {}
    with io.open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n").rstrip("\r")
            if "\t" not in line:
                continue
            url, val = line.split("\t", 1)
            d[url] = None if val == "PARSE_ERROR" else val
    return d


def compare(a: dict, b: dict, urls: list[str], name: str) -> list[tuple[str, str | None, str | None]]:
    accept_mismatch = 0
    output_mismatch = 0
    examples: list[tuple[str, str | None, str | None]] = []
    all_mismatches: list[tuple[str, str | None, str | None]] = []
    for u in urls:
        va, vb = a.get(u), b.get(u)
        mismatched = False
        if (va is None) != (vb is None):
            accept_mismatch += 1
            mismatched = True
        elif va is not None and vb is not None and va != vb:
            output_mismatch += 1
            mismatched = True
        if mismatched:
            all_mismatches.append((u, va, vb))
            if len(examples) < 20:
                examples.append((u, va, vb))
    print(f"--- {name} --- accept_mismatch={accept_mismatch} output_mismatch={output_mismatch}")
    for u, va, vb in examples:
        print(f"  {u}\t{va!r}\tvs\t{vb!r}")
    return all_mismatches


LTR_ALLOWED_BIDI = {"L", "EN", "ES", "CS", "ET", "ON", "BN", "NSM"}


def classify_ada292_vs_ada400_mismatches(
    ada292: dict, pyada400: dict, urls: list[str]
) -> tuple[list, list]:
    """Splits the ada292-vs-ada-url==4.0.0 mismatches into two evidence-supported groups
    instead of one blanket "Unicode version" bucket:

    Group A: Ada 2.9.2's own verified LTR-bidi-validation off-by-one bug (its
        `is_label_valid` loop bound is `i < last_non_nsm_char`, so the label's own LAST
        non-NSM character is never checked against the LTR-allowed bidi-property set --
        confirmed by direct inspection of ada-2.9.2.cpp, function `is_label_valid`, and
        reproduced with constructed witnesses `xn--ab-wld` (accepted, bug) vs `xn--ab-uld`
        (correctly rejected, RTL-initial label, different code path) against both the direct
        oracle and live Node). Ada 2.9.2 wrongly ACCEPTS a 2-label case whose swept codepoint
        has bidi direction outside {L,EN,ES,CS,ET,ON,BN,NSM}; ada-url==4.0.0 (bug fixed)
        correctly rejects it.

    Group B: genuine Unicode-codepoint-assignment-boundary difference -- the swept codepoint
        was unassigned in Ada 2.9.2's own (~Unicode-16-era) data but has since been assigned
        (matches the `xn--8g0n`/U+2EBF0 witness's own shape exactly).
    """
    group_a = []
    group_b = []
    for u in urls:
        va, vb = ada292.get(u), pyada400.get(u)
        mismatched = (va is None) != (vb is None) or (
            va is not None and vb is not None and va != vb
        )
        if not mismatched:
            continue
        label = u[len("file://xn--") : -len("/share")] if "xn--" in u else None
        if label is None:
            group_b.append((u, va, vb, "not-an-xn--case"))
            continue
        try:
            decoded = label.encode("ascii").decode("punycode")
        except Exception:
            group_b.append((u, va, vb, "decode-failed"))
            continue
        if len(decoded) >= 2 and decoded[0] == "a":
            swept = decoded[1]
            bidi = unicodedata.bidirectional(swept)
            if bidi and bidi not in LTR_ALLOWED_BIDI and va is not None and vb is None:
                group_a.append((u, swept, hex(ord(swept)), bidi, va, vb))
                continue
        group_b.append((u, va, vb, f"decoded={decoded!r}"))
    return group_a, group_b


def main() -> None:
    node19 = load_node(os.path.join(SCRATCH, "systematic_node_22190.txt"))
    node23 = load_node(os.path.join(SCRATCH, "systematic_node_22232.txt"))
    ada292 = load_bare(os.path.join(SCRATCH, "systematic_ada292.txt"))
    pyada400 = load_bare(os.path.join(SCRATCH, "systematic_pyada_400.txt"))
    pyada1153 = load_bare(os.path.join(SCRATCH, "systematic_pyada_1153.txt"))

    urls = list(node19.keys())
    print("total cases:", len(urls))

    compare(node19, node23, urls, "node19 vs node23 (drift check)")
    compare(node19, ada292, urls, "node19 vs direct Ada 2.9.2 (ORACLE FIDELITY)")
    compare(ada292, pyada400, urls, "direct Ada 2.9.2 vs python ada-url==4.0.0 (current dep)")
    mism_1153 = compare(
        ada292, pyada1153, urls, "direct Ada 2.9.2 vs python ada-url==1.15.3 (DECISIVE -- Strategy A)"
    )

    group_a, group_b = classify_ada292_vs_ada400_mismatches(ada292, pyada400, urls)
    print()
    print(f"--- ada-url==4.0.0 mismatch reclassification ---")
    print(f"Group A (Ada 2.9.2 LTR-bidi off-by-one bug, fixed in 4.0.0): {len(group_a)}")
    print(f"Group B (genuine Unicode-assignment-boundary difference): {len(group_b)}")
    print(f"Total: {len(group_a) + len(group_b)}")

    if mism_1153:
        print()
        print(f"WARNING: ada-url==1.15.3 mismatches against the direct oracle: {len(mism_1153)}")
    else:
        print()
        print("CONFIRMED: ada-url==1.15.3 matches the direct Ada 2.9.2 oracle on every case.")


if __name__ == "__main__":
    main()
